### ISSUE TITLE
resource proxy always create local dir

### ISSUE THREAD

**Issue by amyangfei** [hanfei1991/microcosm#230]
When a worker resource proxy is created, it always initialize a local storage, which will create a local directory, and the directory won't be removed after worker exits.

- Can we make the storage be created lazily
- Or is there any plan to add GC mechanism when the proxy lifecycle is over.

https://github.com/hanfei1991/microcosm/blob/bda04b4163656fd7dadcd000855d73b350d8a853/pkg/resource/broker.go#L86-L93

**Comment by amyangfei** [comment]
@lance6716 Do you have any idea about this issue?

**Comment by lance6716** [comment]
we are planing to add GC mechanism to solve it. Part of it is in https://github.com/hanfei1991/microcosm/pull/223 
cc @liuzix 

If it blocks some tests, I think you can call https://github.com/hanfei1991/microcosm/blob/bda04b4163656fd7dadcd000855d73b350d8a853/pkg/resource/broker.go#L136-L138 when the worker exits, assuming there's no another worker would share this resource

**Comment by nongfushanquan** [comment]
1. each worker will allocated a temporary directory,, which will be removed when worker in the finished status by the executor except the following case
2. a sub directory will created under the worker's root directory when the user new and close a resource . the sub directory will be reserved when worker exit and removed later by the user .
3. if the job in the finished status ,the sub directory  will be removed if the user forget  do it .
