### ISSUE TITLE
duplicate handlers panic

### ISSUE THREAD

**Issue by hanfei1991** [hanfei1991/microcosm#278]
jobmaster init failed because of p2p register handler timemout. and jobmaster reschedule to the same node again, and p2p register handler timeout agian. happend in `16:07:57` and `16:08:16`.
![image](https://user-images.githubusercontent.com/20884546/160797435-35450abf-b78e-4975-9774-a79792872ed9.png)

in `16:08:33` this executor panic because of `duplicate handlers`, this is p2p log:

![image](https://user-images.githubusercontent.com/20884546/160797601-32abecbc-ccb4-488d-972a-327aedec8a73.png)

**Comment by amyangfei** [comment]
Fixed by #279
