### ISSUE TITLE
DoFailoverRPC may return (nil, nil) if no client is found

### ISSUE THREAD

**Issue by liuzix** [hanfei1991/microcosm#369]
[DoFailoverRPC](https://github.com/hanfei1991/microcosm/blob/6f1e01c87b8f7feecd777b43645ef80875b45636/pkg/rpcutil/client.go#L180)

If there is no client, then the function returns `(nil, nil)`, a violation of what the caller would expect.

**Comment by lance6716** [comment]
OK, I will add an error as the initial value soon
