### ISSUE TITLE
[Design of Master] How to implement Resource Manager (and Resource Model).

### ISSUE THREAD

**Issue by hanfei1991** [hanfei1991/microcosm#4]
The Resource Manager is in charge of recording the resource consumption and alloc the free resource for job master.

## Resource Model

I think the biggest problem for now is how to measure the usage of resource. There are three dimension of resource in a SQL workload, that is 

- cpu
- memory
- i/o

I have no idea whether it fits in the cdc/dm workload.

**Comment by nongfushanquan** [comment]
ResourceManager should alway be in running mode, receiving the executor's workload information , accepting the request to allocate executor for new task.
