### ISSUE TITLE
[to-discuss] How should executors know the address of the master's leader.

### ISSUE THREAD

**Issue by hanfei1991** [hanfei1991/microcosm#6]
In TiCDC, all the comminucation are done by etcd, so that's not a problem. In the new **p2p** framework, `MassageRouter` watch the etcd to apply the owner address change.
In DM, non-leader will transfer the request to leader.
In tikv-pd, there is a background thread to update the leader address.

**Comment by nongfushanquan** [comment]
maybe we can follow the dm's method

**Comment by amyangfei** [comment]
This issue has been separated into two parts
- executor needs to know the address change of server master. <- this is what this issue focus
- executor needs to know the address change of other executors. <- focused in https://github.com/hanfei1991/microcosm/issues/73
